### ISSUE TITLE
我理解设计理念跟 solidjs 一致，只不过一些 dom api 和 solidjs 不同，因为在嵌入式下木有这些 api

### ISSUE THREAD

**Issue by this-spring** [yisar/fre3#1]

**Comment by yisar** [comment]
你的理解十分正确√

**Comment by this-spring** [comment]
额 关于 jsx 部分我理解应该可以复用 solidjs 的呀

**Comment by yisar** [comment]
@this-spring 不理解你的意思，jsx 是通用标准，大家都是通用的，为什么要复用 solidjs 的呢？或者说 solidjs 和其它 jsx 有什么不同吗？

**Comment by this-spring** [comment]
> @this-spring 不理解你的意思，jsx 是通用标准，大家都是通用的，为什么要复用 solidjs 的呢？或者说 solidjs 和其它 jsx 有什么不同吗？

额 我看到你的 jsx 解析是自己用 rust 来写的，我理解这部分应该不需要用 rust 吧，solid 的 jsx babel 插件完全可以复用？

**Comment by yisar** [comment]
fre3 只是思路和 solid 类似，但是整个编译器设计是截然不同的
我不想使用 babel 的另一个原因是，rust 可以交叉编译然后运行到任何地方，还可以和c互调用，而 babel 则需要 node 环境，对嵌入式同学来说十分不友好……
